# Matterbridge
matterbridge_bridges:
  discord:
    status:
      Token: '{{lookup("bitwarden", "Discord/autobot")}}'
      Server: 'Status'
      RemoteNickFormat: '{NICK}@{PROTOCOL}'

  api.chat2:
    BindAddress: "0.0.0.0:4242"
    Buffer: 1000
    RemoteNickFormat: "{NICK}@chat2"

matterbridge_gateways:
  - { status: "waku", discord: [{ srv: "status", ch: "waku" }], api: ["chat2"], private: true }
