---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 40abcc62b18ac5127866c9c413491a7b92451cac
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: 6cc6472e32b6dc53d7d854ab5a34d554451bec15
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 7ee51839e6a032e6ca27dfb00951e897b5385609
  scm: git

- name: certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: 4b93ca81043f843d573c43b42f50e7620e81590d
  scm: git

- name: nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: cb2b857ba929cda4a5ba9859bd7de27adafdd16b
  scm: git
