---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 63998e7c92ed2db1dc1522e0bd5ca398c5434e5c
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: 56d92683bda23f75228cc4ac93b5fae47adbabeb
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 7ee51839e6a032e6ca27dfb00951e897b5385609
  scm: git

- name: certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: 4b93ca81043f843d573c43b42f50e7620e81590d
  scm: git

- name: nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: a66b80766b752800c0ffd13eabe5bd3e4931c020
  scm: git
