---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 24dc30dbdf85e6758cb6924074b2f7a0f4541524
  scm: git

- name: swap-file
  src: git@github.com:status-im/infra-role-swap-file.git
  version: 3fb0fb8d313ab388df1b38d516e2ff88b72a2cf7
  scm: git

- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git
  version: 9de1a4265c78d171d31385ae666d3abc99776f8c
  scm: git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git
  version: b711bbabd2dc3d9ce8b1c3a6e5bc785901db9d09
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: 2b3d4e53856d6cc91ae5c5a342fd12f2bb96aa88
  scm: git

- name: certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: 4dc296d6b860a6ca8a8d437ffd60d6f800f0fc7a
  scm: git

- name: nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: c59aaf4c4e50869b1b542dbbacc3b69e5db0f3d7
  scm: git

- name: waku-peers
  src: git@github.com:status-im/infra-role-waku-peers.git
  version: 9d00e1b330ea89253a147a99b463fb42f58e570b
  scm: git
