---
- name: open-ports
  src: git@github.com:status-im/infra-role-open-ports.git
  version: 54125c7d291289aaea51ca313fc694d057d803fa
  scm: git

- name: infra-role-bootstrap
  src: git@github.com:status-im/infra-role-bootstrap.git
  version: 4dfd3e0b32a93e1f07a73c6794684bae21f2e556
  scm: git

- name: infra-role-matterbridge
  src: git@github.com:status-im/infra-role-matterbridge.git
  #version:
  scm: git

- name: consul-service
  src: git@github.com:status-im/infra-role-consul-service.git
  version: b1d5ad5caa7d7a036fd175292fa497175bb7c54c
  scm: git

- name: certbot
  src: git@github.com:status-im/ansible-role-certbot.git
  version: 9eb5685b986a66791c0f06b6dd9c0d1735d54098
  scm: git
